Kate: homework 4 completed
eugene-okulik/katinagon pull request #3
Opened 2024-06-14 18:17 UTC by katinagon

2024-06-15 17:16 UTC, eugene-okulik requested changes
Всё отлично, но одну проверку на внимательность не прошла ))

2024-06-15 17:16 UTC, eugene-okulik commented on homework/kate_goncharova/Homework_4/homework4.py
> +my_dict['dict']['i am a tuple'] = 'кортеж'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-06-16 07:28 UTC, katinagon commented on homework/kate_goncharova/Homework_4/homework4.py
> +my_dict['dict']['i am a tuple'] = 'кортеж'
Поняла, переделаю)

2024-06-17 10:31 UTC, eugene-okulik approved these changes

2024-06-17 10:31 UTC, merged